apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  labels:
    app: ml-app
spec:
  replicas: 1 # testing how much 1 replica can handle 
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: ml-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9001
          name: metrics
        env:
        - name: PORT
          value: "8000"
        - name: DISPATCHER_URL
          value: "http://dispatcher-service:8001"
        resources:
          requests:
            cpu: 1  # DON"T CHANGE EVEN THOUGH IT LOOKS TEMPTING - I KNOW YOU WANT TO BUT DON"T :)
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /    # Create a simple health endpoint
            port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  labels:
    app: ml-app
spec:
  type: ClusterIP
  selector:
    app: ml-app
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: metrics
